[package]
name = "little-chemistry"
version = "1.0.1"
edition = "2021"

license = "MIT"
description = "A CLI game where you combine things to create new ones."

[dependencies]
dirs = "5.0.1"
toml = "0.7.3"
