[item.dirt]
recipe = "$starter"
class = ["ground"]

[item.air]
recipe = "$starter"
class = ["light", "sky", "high", "cool"]

[item.fire]
recipe = "$starter"
class = ["hot", "bright"]

[item.water]
recipe = "$starter"
class = ["liquid", "cool"]

[item.lava]
recipe = [".hot", ".ground"]
class = ["hot", "bright", "ground"]

[item.rock]
recipe = ["#lava", ["#time", ".cool"]]
class = ["hard", "ground", "build"]

[item.metal]
recipe = ["#rock", ".hot"]
class = ["decor", "material"]

[item.hill]
recipe = [".ground", ".ground"]
class = ["ground", "big"]

[item.planet]
recipe = ["#hill", "#hill"]
class = ["ground", "big", "huge"]

[item.light]
recipe = [".bright", ".bright"]
class = ["bright", "light"]

[item.sky]
recipe = ["#air", "#air"]
class = ["light", "bright", "sky"]

[item.space]
recipe = ["#sky", "#sky"]
class = ["light", "bright", "sky", "alien"]

[item.tool]
recipe = ["#rock", "#rock"]
class = ["hurt", "tool"]

[item.lightning]
recipe = [".sky", "#fire"]
class = ["hot", "bright", "sky", "power"]

[item.clay]
recipe = [".liquid", "#dirt"]
class = ["ground"]

[item.life]
recipe = [["#water", "#air"], ["#clay", "#lightning"]]
class = ["life"]

[item.death]
recipe = [[".hot", ".hurt"], ".life"]
class = []

[item.person]
recipe = [
    [
        "#life",
        [
            "#time",
            ".tool",
            "#house",
            ".decor",
        ],
    ],
    [
        "#corpse",
        "#necromancer",
    ],
]
class = ["life", "human"]

[item.village]
recipe = [["#person", "#person"], [".building", ".building"]]
class = ["big"]

[item.worker]
recipe = ["#person", ".tool"]
class = ["life", "human"]

[item.corpse]
recipe = ["#person", "#death"]
class = ["dead"]

[item.bone]
recipe = [".dead", ["#time", "#carnivore"]]
class = ["dead"]

[item.meat]
recipe = [".dead", "#time"]
class = ["dead"]

[item.carnivore]
recipe = ["#meat", "#life"]
class = ["life"]

[item.time]
recipe = ["#life", "#death"]
class = []

[item.plant]
recipe = ["#life", ".ground"]
class = ["plant", "life", "burn"]

[item.tree]
recipe = ["#plant", ["#time", ".big"]]
class = ["plant", "life", "big", "burn"]

[item.wood]
recipe = ["#tree", ".tool"]
class = ["build", "burn"]

[item.house]
recipe = [".build", ["#wood", "#worker"]]
class = ["building", "burn"]

[item.swamp]
recipe = [".plant", ["#clay", "#lake"]]
class = ["big", "liquid", "life"]

[item.lake]
recipe = ["#water", "#water"]
class = ["liquid", "big"]

[item.sand]
recipe = [["#dirt", "#lake"], ["#rock", "#time"]]
class = ["ground"]

[item.hourglass]
recipe = ["#sand", ["#glass", "#time"]]
class = ["decor"]

[item.glass]
recipe = ["#sand", ".hot"]
class = ["build"]

[item.dune]
recipe = ["#sand", "#hill"]
class = ["ground", "big"]

[item.fish]
recipe = [".liquid", "#life"]
class = ["life", "aquatic"]

[item.spoon]
recipe = ["#tool", "#food"]
class = []

[item.food]
recipe = [["#meat", ".hot"], [".plant", ".hot"]]
class = []

[item.lamp]
recipe = ["#glass", ".light"]
class = ["light", "decor"]

[item.fossil]
recipe = [["#time", "#death"], "#clay"]
class = ["ground"]

[item.dust]
recipe = [["#dirt", "#air"], [".burn", ".hot"]]
class = ["ground"]

[item.sawdust]
recipe = [[".tool", "#dust"], "#wood"]
class = []

[item.pulp]
recipe = ["#sawdust", ".liquid"]
class = []

[item.paper]
recipe = ["#pulp", ["#time", "#air", ".hot"]]
class = ["decor"]

[item.pen]
recipe = ["#paper", "#tool"]
class = ["decor"]

[item.dictionary]
recipe = ["#paper", "#pen"]
class = ["decor"]

[item.art]
recipe = [".decor", ["#house", "#person"]]
class = ["decor"]

[item.artist]
recipe = ["#person", ["#art", "#pen"]]
class = ["life"]

[item.fisher]
recipe = [".human", ".aquatic"]
class = ["life", "human"]

[item.brick]
recipe = ["#clay", [".hot", "#time", "#air"]]
class = ["build"]

[item.forest]
recipe = ["#tree", "#tree"]
class = ["burn", "ecosystem"]

[item.teacher]
recipe = ["#dictionary", ".human"]
class = ["life", "human"]

[item.gold]
recipe = [["#metal", "#lightning"], ["#Midas", ".anything"]]
class = ["decor", "money"]

[item.silver]
recipe = ["#metal", "#light"]
class = ["decor", "money"]

[item.moon]
recipe = ["#rock", ["#light", "#sky"]]
class = ["high", "ground", "bright"]

[item.jewel]
recipe = ["#rock", "#glass"]
class = ["decor", "money"]

[item.crown]
recipe = ["#gold", "#jewel"]
class = ["money"]

[item.diadem]
recipe = ["#silver", "#jewel"]
class = ["money"]

[item.king]
recipe = ["#person", "#crown"]
class = ["life", "human", "money"]

[item.queen]
recipe = ["#person", "#diadem"]
class = ["life", "human", "money"]

[item.ash]
recipe = [[".burn", ".hot"], ["#nuke", ".anything"]]
class = []

[item.nuke]
recipe = ["#fire", "#fire"]
class = []

[item.Midas]
recipe = ["#gold", "#king"]
class = ["magic", "life", "human", "money"]

[item.cloud]
recipe = ["#sky", "#water"]
class = ["sky", "high", "weather"]

[item.rain]
recipe = ["#cloud", "#water"]
class = ["sky", "high", "weather"]

[item.storm]
recipe = ["#weather", ["#weather", "#air"]]
class = ["sky", "high", "weather"]

[item.sword]
recipe = ["#tool", "#metal"]
class = ["hurt", "tool"]

[item.warrior]
recipe = ["#person", "#sword"]
class = ["hurt", "life", "person"]

[item.curse]
recipe = ["#death", "#dictionary"]
class = ["magic"]

[item.necromancer]
recipe = ["#curse", "#person"]
class = ["magic", "life", "human"]

[item.wizard]
recipe = [".magic", "#person"]
class = ["magic", "life", "human"]
