[item.dirt]
recipe = "$starter"
class = ["ground"]

[item.air]
recipe = "$starter"
class = ["light", "sky", "high", "cool"]

[item.fire]
recipe = "$starter"
class = ["hot", "bright"]

[item.water]
recipe = "$starter"
class = ["liquid", "cool"]

[item.lava]
recipe = [".hot", ".ground"]
class = ["hot", "bright", "ground"]

[item.rock]
recipe = ["#lava", ["#time", ".cool"]]
class = ["hard", "ground", "build"]

[item.hill]
recipe = [".ground", ".ground"]
class = ["ground", "big"]

[item.planet]
recipe = ["#hill", "#hill"]
class = ["ground", "big", "huge"]

[item.light]
recipe = [".bright", ".bright"]
class = ["bright", "light"]

[item.sky]
recipe = ["#air", "#air"]
class = ["light", "bright", "sky"]

[item.space]
recipe = ["#sky", "#sky"]
class = ["light", "bright", "sky", "alien"]

[item.tool]
recipe = ["#rock", "#rock"]
class = ["hurt", "tool"]

[item.lightning]
recipe = [".sky", "#fire"]
class = ["hot", "bright", "sky", "power"]

[item.clay]
recipe = [".liquid", "#dirt"]
class = ["ground"]

[item.life]
recipe = [["#water", "#air"], ["#clay", "#lightning"]]
class = ["life"]

[item.death]
recipe = [[".hot", ".hurt"], ".life"]
class = []

[item.person]
recipe = ["#life", ["#time", ".big"]]
class = ["life", "human"]

[item.village]
recipe = [["#person", "#person"], [".building", ".building"]]
class = ["big"]

[item.worker]
recipe = ["#person", ".tool"]
class = ["life", "human"]

[item.corpse]
recipe = ["#person", "#death"]
class = ["dead"]

[item.bone]
recipe = [".dead", ["#time", "#carnivore"]]
class = ["dead"]

[item.meat]
recipe = [".dead", "#time"]
class = ["dead"]

[item.carnivore]
recipe = ["#meat", "#life"]
class = ["life"]

[item.time]
recipe = ["#life", "#death"]
class = []

[item.plant]
recipe = ["#life", ".ground"]
class = ["plant", "life"]

[item.tree]
recipe = ["#plant", ["#time", ".big"]]
class = ["plant", "life", "big"]

[item.wood]
recipe = ["#tree", ".tool"]
class = ["build"]

[item.house]
recipe = [".build", ["#wood", "#worker"]]
class = ["building"]

[item.swamp]
recipe = [".plant", ["#clay", "#lake"]]
class = ["big", "liquid", "life"]

[item.lake]
recipe = ["#water", "#water"]
class = ["liquid", "big"]
